# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class PxUILayout(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(755, 330)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(755, 330))
        MainWindow.setMaximumSize(QtCore.QSize(755, 330))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 230, 241, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.buttonsLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.buttonsLayout.setContentsMargins(0, 0, 0, 0)
        self.buttonsLayout.setObjectName("buttonsLayout")
        self.importButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.importButton.setObjectName("importButton")
        self.buttonsLayout.addWidget(self.importButton)
        self.exportButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.exportButton.setObjectName("exportButton")
        self.buttonsLayout.addWidget(self.exportButton)
        self.fileTable = QtWidgets.QTableView(self.centralwidget)
        self.fileTable.setGeometry(QtCore.QRect(0, 1, 541, 221))
        self.fileTable.setObjectName("fileTable")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(550, 0, 201, 80))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.ExportTypeLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.ExportTypeLayout.setContentsMargins(0, 0, 0, 0)
        self.ExportTypeLayout.setObjectName("ExportTypeLayout")
        self.ExportTypeLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.ExportTypeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ExportTypeLabel.setObjectName("ExportTypeLabel")
        self.ExportTypeLayout.addWidget(self.ExportTypeLabel)
        self.line = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.ExportTypeLayout.addWidget(self.line)
        self.ButtonsLayout = QtWidgets.QHBoxLayout()
        self.ButtonsLayout.setObjectName("ButtonsLayout")
        self.txtButton = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.txtButton.setChecked(True)
        self.txtButton.setObjectName("txtButton")
        self.ButtonsLayout.addWidget(self.txtButton)
        self.csvButton = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.csvButton.setObjectName("csvButton")
        self.ButtonsLayout.addWidget(self.csvButton)
        self.xlsxButton = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.xlsxButton.setObjectName("xlsxButton")
        self.ButtonsLayout.addWidget(self.xlsxButton)
        self.ExportTypeLayout.addLayout(self.ButtonsLayout)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(550, 80, 201, 121))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.namespaceLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.namespaceLayout.setContentsMargins(0, 0, 0, 0)
        self.namespaceLayout.setObjectName("namespaceLayout")
        self.namespaceLabel = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.namespaceLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.namespaceLabel.setObjectName("namespaceLabel")
        self.namespaceLayout.addWidget(self.namespaceLabel)
        self.line_2 = QtWidgets.QFrame(self.verticalLayoutWidget_2)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.namespaceLayout.addWidget(self.line_2)
        self.defaultButton = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.defaultButton.setChecked(True)
        self.defaultButton.setObjectName("defaultButton")
        self.namespaceLayout.addWidget(self.defaultButton)
        self.englishButton = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.englishButton.setObjectName("englishButton")
        self.namespaceLayout.addWidget(self.englishButton)
        self.russianButton = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.russianButton.setObjectName("russianButton")
        self.namespaceLayout.addWidget(self.russianButton)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 755, 32))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.progressBar = QtWidgets.QProgressBar(MainWindow)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.addPermanentWidget(self.progressBar())
        self.progressBar.setGeometry(30, 40, 200, 25)
        self.progressBar.setValue(50)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionImport = QtWidgets.QAction(MainWindow)
        self.actionImport.setObjectName("actionImport")
        self.actionExport = QtWidgets.QAction(MainWindow)
        self.actionExport.setObjectName("actionExport")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionImport)
        self.menuFile.addAction(self.actionExport)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PxParser"))
        self.importButton.setText(_translate("MainWindow", "Import"))
        self.exportButton.setText(_translate("MainWindow", "Export"))
        self.ExportTypeLabel.setText(_translate("MainWindow", "Export file type"))
        self.txtButton.setText(_translate("MainWindow", ".txt"))
        self.csvButton.setText(_translate("MainWindow", ".csv"))
        self.xlsxButton.setText(_translate("MainWindow", ".xlsx"))
        self.namespaceLabel.setText(_translate("MainWindow", "Namespace locale"))
        self.defaultButton.setText(_translate("MainWindow", "Default"))
        self.englishButton.setText(_translate("MainWindow", "English"))
        self.russianButton.setText(_translate("MainWindow", "Russian"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionImport.setText(_translate("MainWindow", "Import"))
        self.actionExport.setText(_translate("MainWindow", "Export"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))

class UITest(QtWidgets.QMainWindow, PxUILayout):
    def __init__(self):
        super().__init__()
        self.setupUi(self)
        self.setup_actions()

    def setup_actions(self):
        self.actionExit.setShortcut('Ctrl+Q')
        self.actionExit.setStatusTip('Quit PxParser')
        self.actionExit.triggered.connect(self.close)

        self.actionImport.setShortcut('Ctrl+I')
        self.actionImport.setStatusTip('Import file')
        self.actionImport.triggered.connect(self.get_file_path)

        self.actionExport.setShortcut('Ctrl+E')
        self.actionExport.setStatusTip('Export selected files')
        self.actionExport.triggered.connect(self.export)

    '''def setup_buttons(self):
        self.txtButton.'''
        
    def get_file_path(self):
        fname = QtWidgets.QFileDialog.getOpenFileName(self, 'Open file', 
   'c:\\',"Log files (*.bin *.ulg)")
        print(fname)

    def export(self):
        pass




def main():
    app = QtWidgets.QApplication([])  # Новый экземпляр QApplication
    window = UITest()  # Создаём объект класса ExampleApp
    window.statusBar().showMessage('Ready')
    window.show()  # Показываем окно
    app.exec_()  # и запускаем приложение

if __name__ == '__main__':  # Если мы запускаем файл напрямую, а не импортируем
    main()  # то запускаем функцию main()